### ISSUE TITLE
Error while setting up platform gree 

### ISSUE THREAD

**Issue by ardeus-ua** [xTCx/gree-python-api#1]
HA 0.75.3

`Wed Aug 15 2018 00:25:55 GMT+0300 (Eastern European Summer Time)

Error while setting up platform gree
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/climate/gree.py", line 116, in async_setup_platform
    import gree
  File "/srv/homeassistant/lib/python3.5/site-packages/gree/__init__.py", line 3, in <module>
    from .gree_device import GreeDevice
  File "/srv/homeassistant/lib/python3.5/site-packages/gree/gree_device.py", line 196
    raise UnexpectedResponse(f"Pack parameter 'r' is different than expected "
                                                                             ^
SyntaxError: invalid syntax`

**Comment by ardeus-ua** [comment]
issue appears only on python 3.5.3, after the upgrade to 3.7.0 everything works
